//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::conversation::Entity as Conversation;
pub use super::file_msg::Entity as FileMsg;
pub use super::group::Entity as Group;
pub use super::message::Entity as Message;
pub use super::user::Entity as User;
pub use super::user_group::Entity as UserGroup;
