//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "message_enum")]
pub enum MessageEnum {
    #[sea_orm(string_value = "File")]
    File,
    #[sea_orm(string_value = "Image")]
    Image,
    #[sea_orm(string_value = "Text")]
    Text,
}
